import type { RequiredDataFromCollectionSlug } from 'payload'

// Used for pre-seeded property content
export const propertiesSeed: Partial<RequiredDataFromCollectionSlug<'properties'>>[] = [
  {
    slug: 'modern-downtown-condo',
    _status: 'published',
    title: 'Modern Downtown Condo with City Views',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Experience luxury urban living in this stunning downtown condominium. Featuring floor-to-ceiling windows, high-end finishes, and breathtaking city views. The open-concept design creates a perfect flow between living, dining, and kitchen areas. Building amenities include a fitness center, rooftop terrace, and 24/7 concierge service.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 750000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    city: 'San Francisco',
    state: 'California',
    zipCode: '94102',
    propertyType: 'condo',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'security', 'parking', 'ac'],
    address: '123 Market Street',
    gallery: [],
  },
  {
    slug: 'spacious-family-home',
    _status: 'published',
    title: 'Spacious Family Home in Suburban Paradise',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Welcome to this beautiful family home nestled in a quiet suburban neighborhood. This spacious 4-bedroom residence features a large backyard, updated kitchen with granite countertops, and a cozy fireplace in the living room. Perfect for families looking for comfort and space.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 1250000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    city: 'Palo Alto',
    state: 'California',
    zipCode: '94301',
    propertyType: 'house',
    listingType: 'sale',
    featured: true,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'garage', 'fireplace', 'laundry', 'pet-friendly'],
    address: '456 Oak Avenue',
    gallery: [],
  },
  {
    slug: 'luxury-penthouse-suite',
    _status: 'published',
    title: 'Luxury Penthouse Suite with Panoramic Views',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Indulge in the pinnacle of luxury living with this exquisite penthouse suite. Boasting panoramic views, a private terrace, chef-grade kitchen, and spa-like bathrooms. The residence includes dedicated elevator access, smart home automation, and premium finishes throughout.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 2500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    city: 'New York',
    state: 'New York',
    zipCode: '10019',
    propertyType: 'condo',
    listingType: 'sale',
    featured: true,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'security', 'parking', 'balcony', 'ac'],
    address: '789 Fifth Avenue',
    gallery: [],
  },
  {
    slug: 'cozy-studio-loft',
    _status: 'published',
    title: 'Cozy Studio Loft in Arts District',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'A charming studio loft in the heart of the Arts District. Features exposed brick walls, high ceilings, and large industrial windows that flood the space with natural light. Walking distance to galleries, restaurants, and nightlife.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 3500,
    bedrooms: 0,
    bathrooms: 1,
    area: 650,
    city: 'Los Angeles',
    state: 'California',
    zipCode: '90013',
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'security', 'laundry', 'pet-friendly'],
    address: '321 Arts Boulevard',
    gallery: [],
  },
  {
    slug: 'beachfront-villa-retreat',
    _status: 'published',
    title: 'Beachfront Villa Retreat',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Wake up to the sound of waves in this stunning beachfront villa. Features direct beach access, infinity pool, outdoor entertaining area, and luxurious master suite. Perfect for those seeking the ultimate coastal lifestyle.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 4500,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    city: 'Malibu',
    state: 'California',
    zipCode: '90265',
    propertyType: 'villa',
    listingType: 'rent',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garden', 'garage', 'gym', 'security'],
    address: '555 Ocean Drive',
    gallery: [],
  },
  {
    slug: 'historic-townhouse-charm',
    _status: 'published',
    title: 'Historic Townhouse with Modern Amenities',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'A beautifully restored historic townhouse blending period charm with modern conveniences. Original hardwood floors, crown molding, and a stunning garden complement the updated kitchen and bathrooms. Located in a prestigious neighborhood.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 850000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    city: 'Boston',
    state: 'Massachusetts',
    zipCode: '02108',
    propertyType: 'townhouse',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'fireplace', 'laundry', 'security'],
    address: '654 Heritage Lane',
    gallery: [],
  },
  {
    slug: 'mountain-cabin-escape',
    _status: 'published',
    title: 'Mountain Cabin Escape',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Escape to the mountains in this cozy cabin retreat. Features stunning mountain views, a wraparound deck, stone fireplace, and rustic yet modern interior. Perfect as a vacation home or year-round residence for nature lovers.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 450000,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    city: 'Aspen',
    state: 'Colorado',
    zipCode: '81611',
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['fireplace', 'garden', 'parking', 'pet-friendly'],
    address: '987 Mountain Road',
    gallery: [],
  },
  {
    slug: 'prime-commercial-space',
    _status: 'published',
    title: 'Prime Commercial Space in Business District',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Prime commercial space located in the heart of the business district. Features open floor plan, high ceilings, modern HVAC system, and ample parking. Ideal for offices, retail, or co-working spaces. High foot traffic area.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 12000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2500,
    city: 'Seattle',
    state: 'Washington',
    zipCode: '98101',
    propertyType: 'commercial',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['security', 'parking', 'ac'],
    address: '147 Business Plaza',
    gallery: [],
  },
  {
    slug: 'development-land-opportunity',
    _status: 'published',
    title: 'Development Land Opportunity',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Rare development opportunity on a prime parcel of land. Zoned for residential or mixed-use development. Excellent location with proximity to schools, shopping, and major highways. All utilities available at the lot line.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 2800000,
    bedrooms: 0,
    bathrooms: 0,
    area: 15000,
    city: 'Austin',
    state: 'Texas',
    zipCode: '78701',
    propertyType: 'land',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['parking'],
    address: '258 Development Way',
    gallery: [],
  },
  {
    slug: 'waterfront-apartment-luxury',
    _status: 'published',
    title: 'Waterfront Apartment with Marina Access',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Stunning waterfront apartment with marina access and breathtaking bay views. Features a gourmet kitchen, spacious living area, and a private balcony perfect for watching sunsets. Resort-style amenities include pool, gym, and concierge.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    city: 'Miami',
    state: 'Florida',
    zipCode: '33139',
    propertyType: 'apartment',
    listingType: 'rent',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'security', 'parking', 'balcony'],
    address: '369 Marina View',
    gallery: [],
  },
  {
    slug: 'starter-home-charmer',
    _status: 'published',
    title: 'Starter Home Charmer with Great Potential',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Perfect starter home with loads of character and potential. Features a welcoming front porch, spacious rooms, and a large backyard. Located in a friendly neighborhood close to parks, schools, and public transit.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    city: 'Portland',
    state: 'Oregon',
    zipCode: '97201',
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'garage', 'laundry', 'pet-friendly'],
    address: '741 Family Street',
    gallery: [],
  },
  {
    slug: 'executive-penthouse-living',
    _status: 'published',
    title: 'Executive Penthouse Living',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'The epitome of urban luxury living. This executive penthouse features soaring ceilings, a wraparound terrace with skyline views, private elevator, wine cellar, and a state-of-the-art home theater. Unmatched sophistication in every detail.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 3200000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    city: 'Chicago',
    state: 'Illinois',
    zipCode: '60611',
    propertyType: 'condo',
    listingType: 'sale',
    featured: true,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'security', 'parking', 'balcony', 'ac'],
    address: '852 Executive Tower',
    gallery: [],
  },
]
