import type { RequiredDataFromCollectionSlug } from 'payload'

function richText(text: string) {
  return {
    root: {
      type: 'root' as const,
      children: [
        {
          type: 'paragraph' as const,
          children: [{ type: 'text' as const, text, version: 1 }],
          direction: 'ltr' as const,
          format: '' as const,
          indent: 0,
          version: 1,
        },
      ],
      direction: 'ltr' as const,
      format: '' as const,
      indent: 0,
      version: 1,
    },
  }
}

// Used for pre-seeded property content
export const propertiesSeed: Partial<RequiredDataFromCollectionSlug<'properties'>>[] = [
  {
    slug: 'modern-downtown-condo',
    _status: 'published',
    title: 'Modern Downtown Condo with City Views',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Experience luxury urban living in this stunning downtown condominium. Featuring floor-to-ceiling windows, high-end finishes, and breathtaking city views. The open-concept design creates a perfect flow between living, dining, and kitchen areas. Building amenities include a fitness center, rooftop terrace, and 24/7 concierge service.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 750000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    city: 'San Francisco',
    state: 'California',
    zipCode: '94102',
    latitude: 37.7749,
    longitude: -122.4194,
    propertyType: 'condo',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'security', 'parking', 'ac'],
    address: '123 Market Street',
    gallery: [],
  },
  {
    slug: 'spacious-family-home',
    _status: 'published',
    title: 'Spacious Family Home in Suburban Paradise',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Welcome to this beautiful family home nestled in a quiet suburban neighborhood. This spacious 4-bedroom residence features a large backyard, updated kitchen with granite countertops, and a cozy fireplace in the living room. Perfect for families looking for comfort and space.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 1250000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    city: 'Palo Alto',
    state: 'California',
    zipCode: '94301',
    latitude: 37.4419,
    longitude: -122.143,
    propertyType: 'house',
    listingType: 'sale',
    featured: true,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'garage', 'fireplace', 'laundry', 'pet-friendly'],
    address: '456 Oak Avenue',
    gallery: [],
  },
  {
    slug: 'luxury-penthouse-suite',
    _status: 'published',
    title: 'Luxury Penthouse Suite with Panoramic Views',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Indulge in the pinnacle of luxury living with this exquisite penthouse suite. Boasting panoramic views, a private terrace, chef-grade kitchen, and spa-like bathrooms. The residence includes dedicated elevator access, smart home automation, and premium finishes throughout.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 2500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    city: 'New York',
    state: 'New York',
    zipCode: '10019',
    latitude: 40.7648,
    longitude: -73.9732,
    propertyType: 'condo',
    listingType: 'sale',
    featured: true,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'security', 'parking', 'balcony', 'ac'],
    address: '789 Fifth Avenue',
    gallery: [],
  },
  {
    slug: 'cozy-studio-loft',
    _status: 'published',
    title: 'Cozy Studio Loft in Arts District',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'A charming studio loft in the heart of the Arts District. Features exposed brick walls, high ceilings, and large industrial windows that flood the space with natural light. Walking distance to galleries, restaurants, and nightlife.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 3500,
    bedrooms: 0,
    bathrooms: 1,
    area: 650,
    city: 'Los Angeles',
    state: 'California',
    zipCode: '90013',
    latitude: 34.0407,
    longitude: -118.2468,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'security', 'laundry', 'pet-friendly'],
    address: '321 Arts Boulevard',
    gallery: [],
  },
  {
    slug: 'beachfront-villa-retreat',
    _status: 'published',
    title: 'Beachfront Villa Retreat',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Wake up to the sound of waves in this stunning beachfront villa. Features direct beach access, infinity pool, outdoor entertaining area, and luxurious master suite. Perfect for those seeking the ultimate coastal lifestyle.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 4500,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    city: 'Malibu',
    state: 'California',
    zipCode: '90265',
    latitude: 34.0259,
    longitude: -118.7798,
    propertyType: 'villa',
    listingType: 'rent',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garden', 'garage', 'gym', 'security'],
    address: '555 Ocean Drive',
    gallery: [],
  },
  {
    slug: 'historic-townhouse-charm',
    _status: 'published',
    title: 'Historic Townhouse with Modern Amenities',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'A beautifully restored historic townhouse blending period charm with modern conveniences. Original hardwood floors, crown molding, and a stunning garden complement the updated kitchen and bathrooms. Located in a prestigious neighborhood.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 850000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    city: 'Boston',
    state: 'Massachusetts',
    zipCode: '02108',
    latitude: 42.3554,
    longitude: -71.0655,
    propertyType: 'townhouse',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'fireplace', 'laundry', 'security'],
    address: '654 Heritage Lane',
    gallery: [],
  },
  {
    slug: 'mountain-cabin-escape',
    _status: 'published',
    title: 'Mountain Cabin Escape',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Escape to the mountains in this cozy cabin retreat. Features stunning mountain views, a wraparound deck, stone fireplace, and rustic yet modern interior. Perfect as a vacation home or year-round residence for nature lovers.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 450000,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    city: 'Aspen',
    state: 'Colorado',
    zipCode: '81611',
    latitude: 39.1911,
    longitude: -106.8175,
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['fireplace', 'garden', 'parking', 'pet-friendly'],
    address: '987 Mountain Road',
    gallery: [],
  },
  {
    slug: 'prime-commercial-space',
    _status: 'published',
    title: 'Prime Commercial Space in Business District',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Prime commercial space located in the heart of the business district. Features open floor plan, high ceilings, modern HVAC system, and ample parking. Ideal for offices, retail, or co-working spaces. High foot traffic area.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 12000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2500,
    city: 'Seattle',
    state: 'Washington',
    zipCode: '98101',
    latitude: 47.6062,
    longitude: -122.3321,
    propertyType: 'commercial',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['security', 'parking', 'ac'],
    address: '147 Business Plaza',
    gallery: [],
  },
  {
    slug: 'development-land-opportunity',
    _status: 'published',
    title: 'Development Land Opportunity',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Rare development opportunity on a prime parcel of land. Zoned for residential or mixed-use development. Excellent location with proximity to schools, shopping, and major highways. All utilities available at the lot line.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 2800000,
    bedrooms: 0,
    bathrooms: 0,
    area: 15000,
    city: 'Austin',
    state: 'Texas',
    zipCode: '78701',
    latitude: 30.2672,
    longitude: -97.7431,
    propertyType: 'land',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['parking'],
    address: '258 Development Way',
    gallery: [],
  },
  {
    slug: 'waterfront-apartment-luxury',
    _status: 'published',
    title: 'Waterfront Apartment with Marina Access',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Stunning waterfront apartment with marina access and breathtaking bay views. Features a gourmet kitchen, spacious living area, and a private balcony perfect for watching sunsets. Resort-style amenities include pool, gym, and concierge.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    city: 'Miami',
    state: 'Florida',
    zipCode: '33139',
    latitude: 25.7907,
    longitude: -80.13,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'security', 'parking', 'balcony'],
    address: '369 Marina View',
    gallery: [],
  },
  {
    slug: 'starter-home-charmer',
    _status: 'published',
    title: 'Starter Home Charmer with Great Potential',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Perfect starter home with loads of character and potential. Features a welcoming front porch, spacious rooms, and a large backyard. Located in a friendly neighborhood close to parks, schools, and public transit.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    city: 'Portland',
    state: 'Oregon',
    zipCode: '97201',
    latitude: 45.5152,
    longitude: -122.6784,
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'garage', 'laundry', 'pet-friendly'],
    address: '741 Family Street',
    gallery: [],
  },
  {
    slug: 'executive-penthouse-living',
    _status: 'published',
    title: 'Executive Penthouse Living',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'The epitome of urban luxury living. This executive penthouse features soaring ceilings, a wraparound terrace with skyline views, private elevator, wine cellar, and a state-of-the-art home theater. Unmatched sophistication in every detail.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    price: 3200000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    city: 'Chicago',
    state: 'Illinois',
    zipCode: '60611',
    latitude: 41.8925,
    longitude: -87.6245,
    propertyType: 'condo',
    listingType: 'sale',
    featured: true,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'security', 'parking', 'balcony', 'ac'],
    address: '852 Executive Tower',
    gallery: [],
  },
  {
    slug: 'brooklyn-brownstone-classic',
    _status: 'published',
    title: 'Classic Brooklyn Brownstone with Garden',
    description: richText(
      'Beautifully restored Brooklyn brownstone featuring original woodwork, exposed brick, and a private garden. Three floors of living space with modern updates throughout. Steps from shops, restaurants, and Prospect Park.',
    ),
    price: 1950000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2600,
    city: 'Brooklyn',
    state: 'New York',
    zipCode: '11217',
    latitude: 40.6782,
    longitude: -73.9442,
    propertyType: 'townhouse',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'fireplace', 'laundry', 'pet-friendly'],
    address: '238 Park Place',
    gallery: [],
  },
  {
    slug: 'scottsdale-desert-oasis',
    _status: 'published',
    title: 'Scottsdale Desert Oasis with Pool',
    description: richText(
      'Stunning desert contemporary home with resort-style backyard featuring a heated pool, spa, and outdoor kitchen. Open floor plan with walls of glass bringing the desert landscape inside. Gated community with golf course access.',
    ),
    price: 875000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    city: 'Scottsdale',
    state: 'Arizona',
    zipCode: '85255',
    latitude: 33.6293,
    longitude: -111.8895,
    propertyType: 'house',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garage', 'ac', 'garden', 'security'],
    address: '4521 Desert Ridge Drive',
    gallery: [],
  },
  {
    slug: 'denver-loft-renovation',
    _status: 'published',
    title: 'Renovated Industrial Loft in RiNo District',
    description: richText(
      "Converted warehouse loft in Denver's trendy River North Art District. Soaring 16-foot ceilings, polished concrete floors, and a chef's kitchen with waterfall island. Rooftop deck with mountain views. Walk to breweries and galleries.",
    ),
    price: 5200,
    bedrooms: 1,
    bathrooms: 1,
    area: 1100,
    city: 'Denver',
    state: 'Colorado',
    zipCode: '80205',
    latitude: 39.7642,
    longitude: -104.9811,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'parking', 'laundry', 'pet-friendly', 'ac'],
    address: '1875 Blake Street',
    gallery: [],
  },
  {
    slug: 'nashville-colonial-estate',
    _status: 'published',
    title: 'Elegant Colonial Estate in Belle Meade',
    description: richText(
      "Grand colonial estate on over an acre of manicured grounds. Features a grand foyer, formal dining room, chef's kitchen, home office, and a finished basement. The backyard includes a pool, cabana, and mature landscaping.",
    ),
    price: 2100000,
    bedrooms: 6,
    bathrooms: 5,
    area: 5400,
    city: 'Nashville',
    state: 'Tennessee',
    zipCode: '37205',
    latitude: 36.0964,
    longitude: -86.8656,
    propertyType: 'house',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garden', 'garage', 'fireplace', 'security'],
    address: '901 Belle Meade Boulevard',
    gallery: [],
  },
  {
    slug: 'san-diego-coastal-condo',
    _status: 'published',
    title: 'Coastal Condo with Ocean Breezes',
    description: richText(
      'Bright and airy coastal condo just blocks from the beach. Updated with quartz countertops, new flooring, and fresh paint throughout. Enjoy the ocean breezes from your private balcony. Community pool and BBQ area.',
    ),
    price: 625000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    city: 'San Diego',
    state: 'California',
    zipCode: '92109',
    latitude: 32.7936,
    longitude: -117.2536,
    propertyType: 'condo',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'balcony', 'parking', 'ac', 'laundry'],
    address: '3344 Mission Boulevard',
    gallery: [],
  },
  {
    slug: 'atlanta-midtown-highrise',
    _status: 'published',
    title: 'Midtown Atlanta Highrise with Skyline Views',
    description: richText(
      'Sleek and modern highrise apartment in the heart of Midtown Atlanta. Floor-to-ceiling windows offer panoramic skyline views. Walking distance to Piedmont Park, MARTA station, and world-class dining. Resort amenities included.',
    ),
    price: 3800,
    bedrooms: 2,
    bathrooms: 2,
    area: 1250,
    city: 'Atlanta',
    state: 'Georgia',
    zipCode: '30309',
    latitude: 33.7866,
    longitude: -84.3832,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'security', 'parking', 'ac'],
    address: '1065 Peachtree Street NE',
    gallery: [],
  },
  {
    slug: 'savannah-historic-mansion',
    _status: 'published',
    title: 'Historic Savannah Mansion on the Square',
    description: richText(
      "Magnificent antebellum mansion overlooking one of Savannah's iconic squares. Meticulously restored with original heart pine floors, ornate plasterwork, and period mantels. Carriage house and courtyard garden included.",
    ),
    price: 1650000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4100,
    city: 'Savannah',
    state: 'Georgia',
    zipCode: '31401',
    latitude: 32.0809,
    longitude: -81.0912,
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['garden', 'fireplace', 'security', 'laundry', 'parking'],
    address: '14 Monterey Square',
    gallery: [],
  },
  {
    slug: 'austin-lakefront-retreat',
    _status: 'published',
    title: 'Lakefront Retreat on Lake Travis',
    description: richText(
      'Contemporary lakefront home with private dock on Lake Travis. Floor-to-ceiling windows frame stunning lake views. Open-concept living, gourmet kitchen, and a multi-level deck for entertaining. Minutes from downtown Austin.',
    ),
    price: 1450000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    city: 'Austin',
    state: 'Texas',
    zipCode: '78732',
    latitude: 30.3948,
    longitude: -97.9206,
    propertyType: 'house',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garden', 'garage', 'balcony', 'pet-friendly'],
    address: '7200 Comanche Trail',
    gallery: [],
  },
  {
    slug: 'dc-dupont-circle-flat',
    _status: 'published',
    title: 'Charming Flat Near Dupont Circle',
    description: richText(
      'Stylish one-bedroom flat in the vibrant Dupont Circle neighborhood. Features hardwood floors, updated kitchen, in-unit washer/dryer, and a sunny reading nook. Walk score of 97 — everything you need is at your doorstep.',
    ),
    price: 2950,
    bedrooms: 1,
    bathrooms: 1,
    area: 750,
    city: 'Washington',
    state: 'District of Columbia',
    zipCode: '20036',
    latitude: 38.9096,
    longitude: -77.0434,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['laundry', 'ac', 'pet-friendly', 'security'],
    address: '1520 P Street NW',
    gallery: [],
  },
  {
    slug: 'phoenix-modern-ranch',
    _status: 'published',
    title: 'Mid-Century Modern Ranch in Arcadia',
    description: richText(
      'Beautifully updated mid-century modern ranch in the coveted Arcadia neighborhood. Clean lines, walls of glass, and a resort-style backyard with pool and citrus trees. New roof, updated electrical, and refinished terrazzo floors.',
    ),
    price: 785000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    city: 'Phoenix',
    state: 'Arizona',
    zipCode: '85018',
    latitude: 33.5088,
    longitude: -111.9678,
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garage', 'garden', 'ac', 'pet-friendly'],
    address: '4402 E Calle Redonda',
    gallery: [],
  },
  {
    slug: 'minneapolis-warehouse-loft',
    _status: 'published',
    title: 'North Loop Warehouse Loft',
    description: richText(
      "Expansive warehouse loft in Minneapolis' trendy North Loop neighborhood. Original timber beams and columns, oversized windows, and an open floor plan perfect for entertaining. Heated underground parking included.",
    ),
    price: 4100,
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    city: 'Minneapolis',
    state: 'Minnesota',
    zipCode: '55401',
    latitude: 44.9862,
    longitude: -93.2718,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['gym', 'parking', 'laundry', 'security', 'pet-friendly'],
    address: '212 N 1st Street',
    gallery: [],
  },
  {
    slug: 'charleston-waterfront-villa',
    _status: 'published',
    title: 'Waterfront Villa on Charleston Harbor',
    description: richText(
      'Exquisite waterfront villa with unobstructed harbor views. Lowcountry architecture meets modern luxury with a gourmet kitchen, custom millwork, and a deep piazza for enjoying sunsets. Private dock and boat lift included.',
    ),
    price: 3200000,
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    city: 'Charleston',
    state: 'South Carolina',
    zipCode: '29401',
    latitude: 32.7765,
    longitude: -79.9311,
    propertyType: 'villa',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garden', 'garage', 'security', 'balcony'],
    address: '30 East Battery',
    gallery: [],
  },
  {
    slug: 'dallas-uptown-studio',
    _status: 'published',
    title: 'Uptown Dallas Designer Studio',
    description: richText(
      "Sleek designer studio in the heart of Uptown Dallas. Custom built-ins maximize space, chef's kitchen with premium appliances, and a Juliet balcony overlooking McKinney Avenue. Walk to Katy Trail and top restaurants.",
    ),
    price: 2200,
    bedrooms: 0,
    bathrooms: 1,
    area: 580,
    city: 'Dallas',
    state: 'Texas',
    zipCode: '75201',
    latitude: 32.7993,
    longitude: -96.8019,
    propertyType: 'apartment',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'parking', 'ac', 'laundry'],
    address: '2525 McKinney Avenue',
    gallery: [],
  },
  {
    slug: 'tahoe-ski-chalet',
    _status: 'published',
    title: 'Lake Tahoe Ski Chalet',
    description: richText(
      'Stunning ski chalet with breathtaking views of Lake Tahoe and the surrounding Sierra peaks. Vaulted ceilings with exposed beams, floor-to-ceiling stone fireplace, and a hot tub on the deck. Ski-in/ski-out access to Heavenly Resort.',
    ),
    price: 1850000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    city: 'South Lake Tahoe',
    state: 'California',
    zipCode: '96150',
    latitude: 38.9332,
    longitude: -119.9843,
    propertyType: 'house',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['fireplace', 'garage', 'garden', 'parking', 'pet-friendly'],
    address: '1200 Ski Run Boulevard',
    gallery: [],
  },
  {
    slug: 'houston-medical-center-condo',
    _status: 'published',
    title: 'Modern Condo Near Texas Medical Center',
    description: richText(
      'Contemporary condo in a luxury high-rise near the Texas Medical Center and Hermann Park. Open layout with premium finishes, floor-to-ceiling windows, and a private balcony. Building features valet, concierge, and a rooftop pool.',
    ),
    price: 520000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1150,
    city: 'Houston',
    state: 'Texas',
    zipCode: '77030',
    latitude: 29.7069,
    longitude: -95.3986,
    propertyType: 'condo',
    listingType: 'sale',
    featured: false,
    featuredSold: true,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'gym', 'security', 'parking', 'balcony'],
    address: '1600 Holcombe Boulevard',
    gallery: [],
  },
  {
    slug: 'philadelphia-rittenhouse-townhome',
    _status: 'published',
    title: 'Rittenhouse Square Townhome',
    description: richText(
      "Elegant townhome just steps from Rittenhouse Square. Four stories of refined living with original marble fireplaces, a chef's kitchen, and a private rooftop deck with city views. One of the most coveted locations in Philadelphia.",
    ),
    price: 1375000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zipCode: '19103',
    latitude: 39.9496,
    longitude: -75.1718,
    propertyType: 'townhouse',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['fireplace', 'laundry', 'security', 'balcony', 'ac'],
    address: '1820 Delancey Place',
    gallery: [],
  },
  {
    slug: 'hawaii-beachfront-estate',
    _status: 'published',
    title: "Beachfront Estate on Maui's North Shore",
    description: richText(
      "Rare beachfront estate on Maui's exclusive North Shore. Tropical modern architecture with indoor-outdoor living, infinity pool overlooking the Pacific, and direct sand access. Lush grounds with fruit trees and a meditation garden.",
    ),
    price: 5800000,
    bedrooms: 5,
    bathrooms: 6,
    area: 5200,
    city: 'Paia',
    state: 'Hawaii',
    zipCode: '96779',
    latitude: 20.9034,
    longitude: -156.3697,
    propertyType: 'villa',
    listingType: 'sale',
    featured: true,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['pool', 'garden', 'security', 'parking', 'ac'],
    address: '88 Hana Highway',
    gallery: [],
  },
  {
    slug: 'detroit-commercial-warehouse',
    _status: 'published',
    title: 'Redeveloped Commercial Warehouse in Corktown',
    description: richText(
      "Fully renovated commercial warehouse in Detroit's booming Corktown district. Open floor plan with exposed brick, steel trusses, and polished concrete. Ideal for creative office, gallery, or retail. Abundant natural light and on-site parking.",
    ),
    price: 8500,
    bedrooms: 0,
    bathrooms: 2,
    area: 3800,
    city: 'Detroit',
    state: 'Michigan',
    zipCode: '48216',
    latitude: 42.3314,
    longitude: -83.0595,
    propertyType: 'commercial',
    listingType: 'rent',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['parking', 'ac', 'security'],
    address: '1415 Michigan Avenue',
    gallery: [],
  },
  {
    slug: 'raleigh-new-construction',
    _status: 'published',
    title: 'New Construction in North Hills',
    description: richText(
      "Brand new construction in Raleigh's sought-after North Hills. Smart home technology throughout, energy-efficient design, quartz countertops, and premium hardwood floors. Covered patio with built-in grill and fenced backyard.",
    ),
    price: 595000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2700,
    city: 'Raleigh',
    state: 'North Carolina',
    zipCode: '27609',
    latitude: 35.8413,
    longitude: -78.6349,
    propertyType: 'house',
    listingType: 'sale',
    featured: false,
    featuredSold: false,
    publishedAt: new Date().toISOString(),
    features: ['garage', 'garden', 'ac', 'laundry', 'pet-friendly'],
    address: '3200 Lassiter Mill Road',
    gallery: [],
  },
]
